parameters:

    ecentria.api.transaction.storage.doctrine.class: Ecentria\Libraries\EcentriaRestBundle\Services\Transaction\Storage\Doctrine

services:

    # Ecentria
    ecentria.api.transaction.storage.doctrine:
        class: %ecentria.api.transaction.storage.doctrine.class%
        arguments:
            - @doctrine
            - @ecentria.api.converter.entity
